version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    versioning-strategy: "auto"
    groups:
      dev-dependencies:
        patterns:
          - "@babel/*"
          - "@testing-library/*"
      production-dependencies:
        patterns:
          - "@sentry/*"
    ignore:
      - dependency-name: "esbuild"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope" 