[[headers]]
  for = "/*"
  [headers.values]
    # Prevent site from being embedded in iframes (clickjacking protection)
    X-Frame-Options = "DENY"
    
    # XSS protection
    X-XSS-Protection = "1; mode=block"
    
    # Prevent MIME type sniffing
    X-Content-Type-Options = "nosniff"
    
    # Referrer policy
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Content Security Policy
    Content-Security-Policy = '''
      default-src 'self';
      script-src 'self' 'unsafe-inline' js.sentry-cdn.com;
      style-src 'self' 'unsafe-inline';
      img-src 'self' data: https:;
      font-src 'self';
      connect-src 'self' sentry.io *.sentry.io;
      media-src 'self';
      object-src 'none';
      frame-src 'none';
      base-uri 'self';
      form-action 'self';
      frame-ancestors 'none';
      upgrade-insecure-requests;
    '''
    
    # Permissions Policy (formerly Feature-Policy)
    Permissions-Policy = '''
      geolocation=(),
      microphone=(),
      camera=(),
      payment=(),
      usb=(),
      fullscreen=(self),
      display-capture=(self)
    '''
    
    # HSTS (uncomment after confirming HTTPS works)
    # Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload" 