name: Website Deployment

on:
  push:
    branches:
      - main
    paths:
      - "website/**"
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - staging
          - prod

permissions:
  id-token: write
  contents: read

env:
  STACK_NAME: PortfolioInfraStack
  AWS_REGION: us-east-1

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./website

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: website/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build website
        run: npm run build

      - name: Debug build output
        run: |
          echo "Contents of dist directory:"
          ls -la dist/
          echo "Current working directory:"
          pwd

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: website-build
          path: website/dist

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'dev' }}

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Debug OIDC claims
        run: |
          echo "GitHub SHA: ${{ github.sha }}"
          echo "GitHub ref: ${{ github.ref }}"
          echo "GitHub repository: ${{ github.repository }}"
          echo "Stage: ${{ github.event.inputs.environment || 'dev' }}"

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: website-build
          path: dist

      - name: Debug downloaded artifact
        run: |
          echo "Contents of dist directory after download:"
          ls -la dist/
          echo "Current working directory:"
          pwd

      - name: Debug file structure
        run: |
          echo "Current working directory:"
          pwd
          echo "\nContents of current directory:"
          ls -la
          echo "\nContents of website directory:"
          ls -la website/
          echo "\nContents of website/src directory:"
          ls -la website/src/
          echo "\nContents of website/src/js directory (if exists):"
          ls -la website/src/js/ || echo "js directory not found or empty"
          echo "\nContents of dist directory:"
          ls -la dist/ || echo "dist directory not found or empty"

      - name: Deploy website files
        run: |
          STAGE="${{ github.event.inputs.environment || 'dev' }}"
          BUCKET_NAME="portfolio-${STAGE}-${{ secrets.AWS_ACCOUNT_ID }}"

          # Get CloudFront distribution ID
          STACK_NAME="PortfolioInfraStack-${STAGE}"
          DISTRIBUTION_ID=$(aws cloudformation describe-stacks \
            --stack-name ${STACK_NAME} \
            --query 'Stacks[0].Outputs[?OutputKey==`DistributionId`].OutputValue' \
            --output text)

          echo "Completely cleaning S3 bucket..."
          aws s3 rm "s3://${BUCKET_NAME}" --recursive

          echo "Waiting to ensure deletion is complete..."
          sleep 10

          echo "Deploying fresh files to S3..."
          # Force sync with exact case sensitivity
          aws s3 sync dist/ "s3://${BUCKET_NAME}" \
            --delete \
            --cache-control "max-age=3600" \
            --exclude ".DS_Store" \
            --exact-timestamps \
            --size-only \
            --no-follow-symlinks

          echo "Verifying new deployment..."
          aws s3 ls "s3://${BUCKET_NAME}" --recursive

          if [ ! -z "$DISTRIBUTION_ID" ]; then
            echo "Invalidating CloudFront cache for distribution: ${DISTRIBUTION_ID}"
            aws cloudfront create-invalidation \
              --distribution-id ${DISTRIBUTION_ID} \
              --paths "/*"
          else
            echo "Warning: Could not find CloudFront distribution ID"
          fi

      - name: Deployment Summary
        run: |
          STAGE="${{ github.event.inputs.environment || 'dev' }}"
          echo "Deployment completed successfully to ${STAGE} environment"
          echo "Timestamp: $(date)"
          echo "Commit: ${{ github.sha }}"
